version: '3.8'

services:
  base_de_datos:
    image: postgres:15
    container_name: gato_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: gato_db
    ports:
      - "5433:5432"

  gestor_db:
    image: adminer
    container_name: gato_adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - base_de_datos